feat(envidencia): actualizar los links
Black-Dot-2024/docs pull request #424
Opened 2024-05-21 05:25 UTC by DHurtado714-itesm

Por favor ve a la tab `Preview` y selecciona la plantilla adecuada:

- [Resolver Issue abierto](?expand=1&template=fix_open_issue.md)
- [Contenido de la Wiki](?expand=1&template=wiki_content.md)

2024-05-21 19:58 UTC, DenisseDB commented
Esta bien, favor de agregar las descripciones faltantes en la tabla de TS

2024-05-21 21:17 UTC, alejandraa-cruiz requested changes

2024-05-21 21:17 UTC, alejandraa-cruiz commented on docs/scampi/ts.md
> +|                                                                                   | TS - SP3.1 Implementar el diseño.
Hola Dani en la práctica 3.1 de TS no es de definición si no de implementación. Aquí iría por ejemplo el proceso de desarrollo, el plan de pruebas y los PRs del proyecto

2024-05-22 18:00 UTC, DenisseDB approved these changes

2024-05-22 18:10 UTC, merged