Feat/checklist verficación
Black-Dot-2024/docs pull request #584
Opened 2024-06-01 00:16 UTC by sebFlores02

# Pull Request: Actualización de Contenido de la Wiki

## Descripción

Se agregó la checklist CHK-BDT-012 Verificación de Reporte de Estado

## Cambios Realizados

- docs/checklist/chk-bdt-012.md

## Verificación

- [x] El versionamiento de la parte superior del documento coincide con la última versión de la tabla de control de cambios del documento.
- [x] El producto de trabajo y su última versión están actualizados en la [Matriz de Configuración](https://docs.google.com/spreadsheets/d/12xtoMNL9ocx4egG_lg_p4_y7RYg-iGxrAkcjjT37WUU/edit#gid=656946687).
- [ ] El producto de trabajo se encuentra registrado en todas las subprácticas del área al que pertence en el SCAMPI.

2024-06-03 20:36 UTC, salgue441 requested changes
Añade análisis en la fase de control de cambios.

2024-06-03 20:39 UTC, salgue441 commented on docs/checklist/chk-bdt-012.md
> +- [ ] Las preguntas del reporte de estado se responden en el orden esperado.
Si la checklist es para hacer el reporte de estado, vale la pena que esto esté aquí?

2024-06-03 20:42 UTC, salgue441 commented on docs/checklist/chk-bdt-012.md
> +- [ ] En caso de que hubiera, se llevaron a cabo las correcciones.
Hay alguna verificación adicional después de hacer las correcciones?

2024-06-03 20:42 UTC, salgue441 commented on docs/checklist/chk-bdt-012.md
> +- [ ] No existen muletillas ni redundancias.
Se está considerando un script?

2024-06-03 22:39 UTC, alejandraa-cruiz requested changes
Importante añadir la checklist al proceso de reporte de estado y por lo tanto a la sección de VER en el cmmi porque es una checklist de verficación. Si quieres platicamos en que prácticas va, pero yo creo sobre todo VER SP 1.3

2024-06-04 03:01 UTC, sebFlores02 commented on docs/checklist/chk-bdt-012.md
> +- [ ] Las preguntas del reporte de estado se responden en el orden esperado.
la checklist no es para hacer el reporte, es para validar su contenido y su calidad

2024-06-04 03:02 UTC, sebFlores02 commented on docs/checklist/chk-bdt-012.md
> +- [ ] En caso de que hubiera, se llevaron a cabo las correcciones.
ahorita le pongo que se vuelve a validar

2024-06-04 03:02 UTC, sebFlores02 commented on docs/checklist/chk-bdt-012.md
> +- [ ] No existen muletillas ni redundancias.
si

2024-06-04 20:42 UTC, alejandraa-cruiz requested changes
la checklist va en departamento jje

2024-06-04 22:48 UTC, DenisseDB approved these changes

2024-06-04 22:48 UTC, salgue441 approved these changes

2024-06-04 22:49 UTC, merged